# The game client (TClient.vcxproj)

set(TClient_SOURCES
    ../../Lib/Own/GameConfig/GameConfig.cpp
    ArenaRanking.cpp
    BattleRankProgressDlg.cpp
    BattleRankTex.cpp
    BRPannels.cpp
    BRRankingDlg.cpp
    BRTeamDlg.cpp
    BRTRanking.cpp
    CompStyleDlg.cpp
    CSHandler.cpp
    CSSender.cpp
    CSSenderAll.cpp
    Curse.cpp
    GuildSkillsDlg.cpp
    HwidManager.cpp
    IPDialog.cpp
    MacroProtection.cpp
    md5.cpp
    Outro.cpp
    PacketSpyAcks.cpp
    PacketSpyDlg.cpp
    SHA1.cpp
    SHA512.cpp
    SmoothScrolling.cpp
    StdAfx.cpp
    TAidCountry.cpp
    TArenaReg.cpp
    TAuctionBasket.cpp
    TAuctionCategory.cpp
    TAuctionCommander.cpp
    TAuctionCtrlList.cpp
    TAuctionInnerFrame.cpp
    TAuctionMainFrame.cpp
    TAuctionMsgBox.cpp
    TAuctionMyBid.cpp
    TAuctionRegist.cpp
    TAuctionSearch.cpp
    TBattleInvenDlg.cpp
    TBFGAlarm.cpp
    TBFGStatus.cpp
    TBlockListDlg.cpp
    TBodGuildRankClass.cpp
    TBodRankClass.cpp
    TBodRankDlg.cpp
    TBodRankTexture.cpp
    TBowBPTradeDlg.cpp
    TBowGuildRankClass.cpp
    TBowRankClass.cpp
    TBowRankingDlg.cpp
    TBowRegisterDlg.cpp
    TBowRegisterWaitingDlg.cpp
    TBowRespawnDlg.cpp
    TBoxOpen.cpp
    TBoxOpenList.cpp
    TCabinetDlg.cpp
    TCandidateFrame.cpp
    TCashCabinetDlg.cpp
    TChallengeEvent.cpp
    TChallengeItem.cpp
    TChallengeWaiting.cpp
    TCharInfoNewDlg.cpp
    TCharInfoNewInner.cpp
    TCharInfoNewPVPDlg.cpp
    TCharInfoNewWarDlg.cpp
    TChatCommander.cpp
    TChatFrame.cpp
    TChatList.cpp
    TChatMenuNew.cpp
    TChatTabButton.cpp
    TCinematicDlg.cpp
    TClient.cpp
    TClientArrow.cpp
    TClientBSP.cpp
    TClientCAM.cpp
    TClientChar.cpp
    TClientCompanion.cpp
    TClientCustomCloak.cpp
    TClientFake.cpp
    TClientFlag.cpp
    TClientGame.cpp
    TClientGate.cpp
    TClientGM.cpp
    TClientGuildMark.cpp
    TClientInven.cpp
    TClientItem.cpp
    TClientKEY.cpp
    TClientMaintain.cpp
    TClientMAP.cpp
    TClientMonster.cpp
    TClientMoveObj.cpp
    TClientMsgBox.cpp
    TClientNET.cpp
    TClientNICEventSink.cpp
    TClientNpc.cpp
    TClientNumber.cpp
    TClientObjBase.cpp
    TClientObject.cpp
    TClientPath.cpp
    TClientPet.cpp
    TClientQClass.cpp
    TClientQuest.cpp
    TClientRecall.cpp
    TClientSession.cpp
    TClientSfx.cpp
    TClientSkill.cpp
    TClientSpolecnik.cpp
    TClientSwitch.cpp
    TClientTalkBox.cpp
    TClientTerm.cpp
    TClientUIBase.cpp
    TClientWebCtrl.cpp
    TClientWnd.cpp
    TColorPicker.cpp
    TCommunityDlg.cpp
    TCompanionAttrs.cpp
    TCompanionInner.cpp
    TCompanionMiniUI.cpp
    TCompanionStats.cpp
    TCraftQuestDlg.cpp
    TCtrlList.cpp
    TCustomCloakDlg.cpp
    TDetailInfo.cpp
    TDetailInfoDlg.cpp
    TDetailInfoManager.cpp
    TDetailNameDlg.cpp
    TDurationFrame.cpp
    TDynamicHelpDlg.cpp
    TFameBaseDlg.cpp
    TFameListDlg.cpp
    TFameRank.cpp
    TFrameGroupBase.cpp
    TGameSettingFrame.cpp
    TGaugePannel.cpp
    TGuildAppInnerFrame.cpp
    TGuildApplicationDlg.cpp
    TGuildCabinetDlg.cpp
    TGuildCmdHelpDlg.cpp
    TGuildCommander.cpp
    TGuildExpDonDlg.cpp
    TGuildJoinNewDlg.cpp
    TGuildMainNewDlg.cpp
    TGuildMarkMakeDlg.cpp
    TGuildMemberFrame.cpp
    TGuildMembersNewDlg.cpp
    TGuildMercenaryNewDlg.cpp
    TGuildMoneyDonDlg.cpp
    TGuildNormalFrame.cpp
    TGuildNotifyDlg.cpp
    TGuildOfferFrame.cpp
    TGuildPointLogFrame.cpp
    TGuildPointRewardFrame.cpp
    TGuildPvPRecordFrame.cpp
    TGuildRegularOffer.cpp
    TGuildRTTypeFrame.cpp
    TGuildSeekFrame.cpp
    TGuildSummaryNewDlg.cpp
    TGuildTacticsOffer.cpp
    TGuildTerritoryFrame.cpp
    TGuildVolunteerFrame.cpp
    TGuildWarInfoNewDlg.cpp
    THelpFrame.cpp
    TInvenDlg.cpp
    TItemCraftDlg.cpp
    TItemExtPeriodDlg.cpp
    TItemGambleDlg.cpp
    TItemRefineDlg.cpp
    TItemRegBox.cpp
    TItemRegGuildDlg.cpp
    TItemRepairDlg.cpp
    TItemSlotBaseDlg.cpp
    TItemUpCashDlg.cpp
    TItemUpDlg.cpp
    TItemUpGaugeDlg.cpp
    TKeySettingDefines.cpp
    TKeySettingDlg.cpp
    TLimitEdit.cpp
    TListEx.cpp
    TMagicItemShopDlg.cpp
    TMailAskMoneyDlg.cpp
    TMailListFrame.cpp
    TMailRecvDlg.cpp
    TMailSendDlg.cpp
    TMailSender.cpp
    TMaintainPannel.cpp
    TMainUI.cpp
    TMessengerBase.cpp
    TMessengerChat.cpp
    TMessengerCommander.cpp
    TMiniDump.cpp
    TMinimapDlg.cpp
    TMiniPopupDlg.cpp
    TMsgChatMemberList.cpp
    TMsgGroupList.cpp
    TNationOption.cpp
    TNetGM.cpp
    TNetHandler.cpp
    TNetSender.cpp
    TNewAuctionHouseDlg.cpp
    TNewQuestDlg.cpp
    TNormalCabinetDlg.cpp
    TNPCTalkDlg.cpp
    TNumberEdit.cpp
    TPartyCommander.cpp
    TPartyItemLottery.cpp
    TPetDlg.cpp
    TPetMakeDlg.cpp
    TPetManageDlg.cpp
    TPopupMenu.cpp
    TPopupNewMenu.cpp
    TPortalShopDlgNew.cpp
    TPotionPannel.cpp
    TPremiumSkillsDlg.cpp
    TPrivateShopDlg.cpp
    TProgressRegDlg.cpp
    TQuestNewDlg.cpp
    TRankingNewDlg.cpp
    TRankingNewMain.cpp
    TRelayHandler.cpp
    TRelaySender.cpp
    TRentSkillDlg.cpp
    TRpcDlg.cpp
    TRpcRewardDlg.cpp
    TRpsRewardList.cpp
    TRSCSDlg.cpp
    TScenePlayer.cpp
    TSecuritySystemDlg.cpp
    TSelectCountry.cpp
    TSettingFrame.cpp
    TShopBaseDlg.cpp
    TShopDlg.cpp
    TShopItem.cpp
    TSiegeEnd.cpp
    TSiegeGodBall.cpp
    TSiegeGodTower.cpp
    TSiegeManager.cpp
    TSiegeUI.cpp
    TSkillDlg.cpp
    TSkygardenEnd.cpp
    TSkygardenMap.cpp
    TSMSDlg.cpp
    TSoulLotteryDlg.cpp
    TSoulLotteryWinDlg.cpp
    TSoulmateFrame.cpp
    TSystemInfo.cpp
    TSystemSettingFrame.cpp
    TTacticsInviteDlg.cpp
    TTextLinkData.cpp
    TTextLinker.cpp
    TTextPopup.cpp
    TTitleDlg.cpp
    TTournament.cpp
    TTournamentEvent.cpp
    TTournamentGage.cpp
    TTournamentMode.cpp
    TTournamentResult.cpp
    TTournamentSelectTarget.cpp
    TTournamentSelectWinner.cpp
    TTradeDlg.cpp
    TUpItemSellDlg.cpp
    TUtilityBarDlg.cpp
    TWelcome.cpp
    TWorldmapDlg.cpp
)

# TClient.dpiaware.manifest = the dpiAware=true part MSBuild adds by default (EnableDpiAwareness).
add_executable(TClient WIN32 ${TClient_SOURCES} TClient.rc TClient.dpiaware.manifest)
target_compile_definitions(TClient PRIVATE WIN32 NEW_IF)
target_include_directories(TClient PRIVATE
    "${CMAKE_CURRENT_SOURCE_DIR}"
    "${TCLIENT_LIB_OWN}/GameConfig"
    "${TCLIENT_LIB_3RD}/HShield/Include"
    "${TCLIENT_LIB_OWN}/TProtocol/Include"
    "${TCLIENT_ROOT}/Client/History Files"
)
target_link_directories(TClient PRIVATE
    "${TCLIENT_LIB_3RD}/HShield/Lib/Win/x86/Multithreaded/Update"
    "${TCLIENT_LIB_3RD}/HShield/Lib/Win/x86/Multithreaded/HShield"
)
target_link_libraries(TClient PRIVATE
    tclient_options
    HwidLib
    EngineLib
    TChart
    TCML
    TComp
    d3d9 d3dx9 dsound dxguid strmiids
    advapi32 imm32 version dbghelp psapi
)
target_link_options(TClient PRIVATE
    /DEBUG
    /INCREMENTAL:NO
    /LARGEADDRESSAWARE
    /SAFESEH:NO
    /OPT:REF
    /OPT:NOICF
    /MAP
    /MAPINFO:EXPORTS
    "/MANIFESTUAC:level='requireAdministrator' uiAccess='false'"
)
# Resources are Korean (Culture=0x0412).
set_source_files_properties(TClient.rc PROPERTIES COMPILE_OPTIONS "/l0x0412" COMPILE_DEFINITIONS KOREA)
